import = ["/home/michael/.config/alacritty/gruvbox.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 12.0

[font.glyph_offset]
x = 1
y = 5

[font.normal]
family = "BlexMono Nerd Font Mono"
style = "Text"

[font.offset]
x = 1
y = 5

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mode = "~Search"
mods = "Shift|Control"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_padding = true
startup_mode = "SimpleFullscreen"
title = "Terminal"
